farao-community/gridcapa-task-manager

.github/workflows/build.yml
.gitignore
Dockerfile
README.md
checkstyle.xml
pom.xml
src/main/java/com/farao_community/farao/gridcapa/task_manager/MinioAdapter.java
src/main/java/com/farao_community/farao/gridcapa/task_manager/MinioConnector.java
src/main/java/com/farao_community/farao/gridcapa/task_manager/MinioNotificationsListener.java
src/main/java/com/farao_community/farao/gridcapa/task_manager/Task.java
src/main/java/com/farao_community/farao/gridcapa/task_manager/TaskManager.java
src/main/java/com/farao_community/farao/gridcapa/task_manager/TaskManagerApplication.java
src/main/java/com/farao_community/farao/gridcapa/task_manager/TaskManagerConfigurationProperties.java
src/main/java/com/farao_community/farao/gridcapa/task_manager/TaskRepository.java
src/main/resources/META-INF/additional-spring-configuration-metadata.json
src/main/resources/application.yml
src/test/java/com/farao_community/farao/gridcapa/task_manager/TaskManagerTest.java
src/test/resources/application.yml

WIP: Initialize task manager, first commit

---

pom.xml
src/main/java/com/farao_community/farao/gridcapa/task_manager/MinioNotificationsListener.java
src/main/java/com/farao_community/farao/gridcapa/task_manager/TaskManager.java
src/main/java/com/farao_community/farao/gridcapa/task_manager/TaskRepository.java
src/main/java/com/farao_community/farao/gridcapa/task_manager/entities/ProcessFile.java
src/main/java/com/farao_community/farao/gridcapa/task_manager/entities/ProcessFileStatus.java
src/test/java/com/farao_community/farao/gridcapa/task_manager/TaskManagerTest.java
src/test/java/com/farao_community/farao/gridcapa/task_manager/TaskProcessFileDeletionTest.java

No
Feature
Handle MinIO file deletion event handling in task manager

Implement MinIO deletion events handling in task manager

---

src/main/resources/application.yml

removing unused rabbit config

---

src/main/java/com/farao_community/farao/gridcapa/task_manager/TaskManager.java
src/main/java/com/farao_community/farao/gridcapa/task_manager/TaskNotifier.java

performance improvement

---

gridcapa-task-manager-api/pom.xml
gridcapa-task-manager-app/pom.xml
pom.xml

Release 0.0.1

---

gridcapa-task-manager-api/src/main/java/com/farao_community/farao/gridcapa/task_manager/api/ProcessEventDto.java
gridcapa-task-manager-api/src/main/java/com/farao_community/farao/gridcapa/task_manager/api/ProcessFileDto.java
gridcapa-task-manager-api/src/main/java/com/farao_community/farao/gridcapa/task_manager/api/TaskDto.java
gridcapa-task-manager-api/src/test/java/com/farao_community/farao/gridcapa/task_manager/api/ProcessEventDtoTest.java
gridcapa-task-manager-api/src/test/java/com/farao_community/farao/gridcapa/task_manager/api/TaskDtoTest.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerController.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskRepository.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessEvent.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessFile.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/Task.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerControllerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskProcessFileDeletionTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessEventTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessFileTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/entities/TaskTest.java

No
Update
Convert all timestamp from LocaleDateTime to OffsetDateTime
Yes , the convertion of timestamp to locale date time should be done in the Gridcapa App
**Other …

Convert timestamp offset date time

---

gridcapa-task-manager-api/src/main/java/com/farao_community/farao/gridcapa/task_manager/api/TaskLogEventUpdate.java
gridcapa-task-manager-api/src/test/java/com/farao_community/farao/gridcapa/task_manager/api/TaskLogEventUpdateTest.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerApplication.java
gridcapa-task-manager-app/src/main/resources/application.yml
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerTest.java

feature : convert slf4j logs to rabbitmq events with binding to calculation task
(if any of the questions/checkboxes don't apply, please delete them …

read business logs from amqp exchange

---

gridcapa-task-manager-api/pom.xml
gridcapa-task-manager-app/pom.xml
pom.xml

Release 0.2.0

---

gridcapa-task-manager-api/src/main/java/com/farao_community/farao/gridcapa/task_manager/api/ProcessEventDto.java

Fix process event IO

---

checkstyle.xml
gridcapa-task-manager-api/pom.xml
gridcapa-task-manager-app/pom.xml
pom.xml

farao-parent-ws upgraded to version 1.3.0 that embeds new versions of spring-boot and spring-cloud. So we can remove spring-cloud dependency management. 
Also updates commons-io version that fixes a vulnerability and postgres jdbc to be up-to-date with literature.
Removed unnecessary dependency on aws-sdk all the related dependencies were in minio already.

Upgrade farao parent

---

gridcapa-task-manager-api/pom.xml
gridcapa-task-manager-app/pom.xml
pom.xml

Prepare release 0 3 0

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessEvent.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/Task.java
gridcapa-task-manager-app/src/main/resources/application.yml
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/entities/TaskTest.java
gridcapa-task-manager-app/src/test/resources/application.yml

Fix messages loss in task manager

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerTest.java

catching error in update task

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskDtoBuilder.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerController.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerControllerTest.java

No
feature
Retrieve a list of tasks based on a business date
No

retrieve a list of tasks based on a business date

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskUpdateNotifier.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskWithStatusUpdate.java
gridcapa-task-manager-app/src/main/resources/application.yml

Handle 2 different bindings for status update (or not) when notifying TaskDto

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerController.java

Delete API entrypoints with ID related to export service POC

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java

Add a lock on methods that access to the database to avoid inconsistencies

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskDtoBuilder.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/configuration/TaskManagerConfigurationProperties.java
gridcapa-task-manager-app/src/main/resources/application.yml
gridcapa-task-manager-app/src/test/resources/application.yml

integrate optional input files feature

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/FileManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerController.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/FileManagerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerControllerTest.java

No
Bug fix
Wrong time in the zip name
No

fix zip name

---

gridcapa-task-manager-api/src/main/java/com/farao_community/farao/gridcapa/task_manager/api/TaskStatus.java

No
Add interrupted and stopping status
No

add interrupted and stopping status

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java

use the returned value of the save function to update task

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/FileManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/configuration/TaskManagerConfigurationProperties.java
gridcapa-task-manager-app/src/main/resources/application.yml
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/FileManagerTest.java
gridcapa-task-manager-app/src/test/resources/application.yml

No
Feature
Make export logs configurable (to be used by all processes).

make export logs configurable

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java

Handle errors in consumers

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/FileManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerController.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/FileManagerTest.java

Generate seperate log file

---

gridcapa-task-manager-api/src/main/java/com/farao_community/farao/gridcapa/task_manager/api/TaskLogEventUpdate.java
gridcapa-task-manager-api/src/test/java/com/farao_community/farao/gridcapa/task_manager/api/TaskLogEventUpdateTest.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerTest.java

Adding prefix in the businesslogger

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/Task.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/comparators/ReverseEventComparator.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerTest.java

inverse event filtering for fronnt end

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskDtoBuilder.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerController.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskRepository.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/Task.java

add new endpoint for global view

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/Task.java

fix broken build after merge, repair imports on Task entity

---

gridcapa-task-manager-api/src/main/java/com/farao_community/farao/gridcapa/task_manager/api/ProcessFileDto.java
gridcapa-task-manager-api/src/test/java/com/farao_community/farao/gridcapa/task_manager/api/ProcessFileDtoTest.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/FileManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskDtoBuilder.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerController.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessFile.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/Task.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerControllerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerTestUtil.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskProcessFileDeletionTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskWithOverlappingProcessFilesTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessFileTest.java
pom.xml

Now save object key and no more presigned url in database

---

gridcapa-task-manager-api/src/main/java/com/farao_community/farao/gridcapa/task_manager/api/TaskDto.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskDtoBuilder.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerController.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/FileEventType.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessFileMinio.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandler.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/MinioHandler.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/StatusHandler.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/FileManagerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerControllerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerTestUtil.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskProcessFileDeletionTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskWithOverlappingProcessFilesTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandlerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/MinioHandlerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/StatusHandlerTest.java

Handle file while process running

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskRepository.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessEvent.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/Task.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandler.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessEventTest.java

improve logging event management in gridcapa

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskRepository.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessEvent.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/Task.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandler.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessEventTest.java

Reverts farao-community/gridcapa-task-manager#64

Revert "improve logging event management in gridcapa"

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/MinioHandler.java

fix bug multiple task launch

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandler.java
gridcapa-task-manager-app/src/main/resources/application.yml
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/DatabasePurgeServiceTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandlerTest.java

Reverts farao-community/gridcapa-task-manager#67

Revert "Optim event task manager"

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandler.java
gridcapa-task-manager-app/src/main/resources/application.yml
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/DatabasePurgeServiceTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandlerTest.java

Optim event task manager is back

---

gridcapa-task-manager-api/src/main/java/com/farao_community/farao/gridcapa/task_manager/api/ProcessEventDto.java
gridcapa-task-manager-api/src/main/java/com/farao_community/farao/gridcapa/task_manager/api/TaskStatus.java
gridcapa-task-manager-api/src/test/java/com/farao_community/farao/gridcapa/task_manager/api/ProcessEventDtoTest.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/FileManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskDtoBuilder.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerApplication.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerController.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessEvent.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/Task.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandler.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/MinioHandler.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/StatusHandler.java
gridcapa-task-manager-app/src/main/resources/application.yml
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/FileManagerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerControllerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessEventTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/entities/TaskTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/MinioHandlerTest.java
gridcapa-task-manager-app/src/test/resources/application.yml

No
feature
- [core cc requirement ] Check if all tasks for a BD are over 
- [core cc requirement ]  Get only RaoRunnerApp logs 

check if all tasks for a BD are over and get RaoRunnerApp logs 

---

.github/workflows/build.yml
.github/workflows/release.yml
Dockerfile
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/DatabasePurgeServiceTest.java
pom.xml

first version java 17

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskDtoBuilder.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskRepository.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessEvent.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/Task.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerControllerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessEventTest.java

Improve business date view hmi performance

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerController.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerControllerTest.java

Add new REST endpoint for manual triggering of data export

---

gridcapa-task-manager-api/src/main/java/com/farao_community/farao/gridcapa/task_manager/api/TaskManagerException.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/FileManager.java
gridcapa-task-manager-app/src/main/resources/logback.xml

Improve exceptions handling and logs

---

gridcapa-task-manager-api/pom.xml
gridcapa-task-manager-app/pom.xml
pom.xml

Next release v1.23.0

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerController.java

Remove INTERRUPTED status for manual export

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskDtoBuilder.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskDtoBuilderTest.java

No
Fix
getListTasksDto always returns 24 tasks (instead of 23/25 depending on days)
Now checks offset at beginning and end of day
No
(if any of the …

added a fix for days with 23 or 25 ts

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/FileManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerController.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/ProcessEvent.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/Task.java
gridcapa-task-manager-app/src/main/resources/application.yml
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/FileManagerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerControllerTest.java
pom.xml

Allow manual upload of input files from HMI

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskDtoBuilder.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskUpdateNotifier.java

fix status updates on hmi for business date view and global view

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/FileManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/configuration/TaskManagerConfigurationProperties.java
gridcapa-task-manager-app/src/main/resources/application.yml
gridcapa-task-manager-app/src/test/resources/application.yml

Change way manual file import uses base path

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskUpdateNotifier.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandler.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/StatusHandler.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandlerTest.java

Fix task update notification

---

gridcapa-task-manager-app/pom.xml
gridcapa-task-manager-app/src/main/resources/application.yml
gridcapa-task-manager-app/src/test/resources/application.yml

Harmonize application.yml

---

gridcapa-task-manager-app/src/main/resources/db/v5.11.0/add_document_id_to_process_file.xml
gridcapa-task-manager-app/src/main/resources/db/v5.11.0/v5.11.0-changelog.xml

Add specific changelog to add column document id to table process file

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/TaskDtoBuilderService.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/TaskService.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/TaskDtoBuilderServiceTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/TaskServiceTest.java
gridcapa-task-manager-app/src/test/resources/application.yml

Fix CSE import bug on launch task if optional absent

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/repository/TaskRepository.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/MinioHandler.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/MinioHandlerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/TaskDtoBuilderServiceTest.java

Optimize task retrieval when receiving new input file

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/FileManager.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerController.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskUpdateNotifier.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/Task.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/repository/ProcessEventRepository.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/repository/TaskRepository.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/DatabasePurgeService.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandler.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/StatusHandler.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/TaskDtoBuilderService.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/TaskService.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/FileManagerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskProcessFileDeletionTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/entities/TaskTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/DatabasePurgeServiceTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandlerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/FileSelectorServiceTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/MinioHandlerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/TaskDtoBuilderServiceTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/TaskServiceTest.java

Stop systematically fetching ProcessEvents

---

gridcapa-task-manager-api/src/main/java/com/farao_community/farao/gridcapa/task_manager/api/ProcessRunDto.java
gridcapa-task-manager-api/src/test/java/com/farao_community/farao/gridcapa/task_manager/api/ProcessRunDtoTest.java
gridcapa-task-manager-api/src/test/java/com/farao_community/farao/gridcapa/task_manager/api/TaskDtoTest.java
gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/service/TaskDtoBuilderService.java

Add pending interrupt feature

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskUpdateNotifier.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskUpdateNotifierTest.java

Delete not used task-updated binding

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/FileManager.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/FileManagerTest.java

Delete broken and redundant log when manual uploading

---

gridcapa-task-manager-app/src/main/resources/application.yml

Signed-off-by: thiriondan <daniel.thirion@rte-france.com>
(cherry picked from commit 0f94cbd9ed15da1108e7d568540a095e9a1a71ea)
(if any of the …

Fix spring boot file size max limit (#115)

---

gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/entities/Task.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/FileManagerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManagerControllerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskProcessFileDeletionTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/TaskWithOverlappingProcessFilesTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/DatabasePurgeServiceTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/EventHandlerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/FileSelectorServiceTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/MinioHandlerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/ParameterServiceTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/StatusHandlerTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/TaskDtoBuilderServiceTest.java
gridcapa-task-manager-app/src/test/java/com/farao_community/farao/gridcapa/task_manager/app/service/TaskServiceTest.java
pom.xml

Signed-off-by: thiriondan <daniel.thirion@rte-france.com>

Upgrade to Spring Boot 3.4.6 & Spring Cloud 2024.0.1
